#!/bin/sh /etc/rc.common
 
USE_PROCD=1
START=99
STOP=85

DAEMON=sgud.sh
PROG=/usr/share/sguclient/$DAEMON

sgud_loader() {

  local enable
  config_get_bool enable $1 enable
  # 有些路由器安装完软件包会自动执行start方法，该判断用于避免还没有设置配置文件导致的错误
  if [ $enable ]; then
        local logtofile
        local autoreconnect
        local username
        local password
        local isptype
        local ifname
        local cmd
        config_get_bool autoreconnect $1 autoreconnect
        config_get_bool noheartbeat $1 noheartbeat
        config_get username $1 username
        config_get password $1 password
        config_get isptype $1 isptype
        config_get ifname $1 ifname
        config_get_bool logtofile $1 logtofile
        if [ $noheartbeat ];  then cmd=$cmd" --noheartbeat";fi
        # 如果用户选择不开启重连,那么sgud.sh只会启动一次sguclient
        if [ $autoreconnect ];  then cmd=$cmd" --auto";fi
        procd_open_instance
        procd_set_param pidfile /var/run/${DAEMON}.pid # 用pid文件做一个flag
        procd_set_param command bash "$PROG" -u $username -p $password -i $isptype --device $ifname $cmd
        # threshold：异常失败边界值3600；timeout：重启延迟时间1；retry：失败重启次数5
        procd_set_param respawn 3600 1 5
        procd_close_instance
        echo "SGUClient has started."
  fi

}
start_service(){

  config_load sguclient
  config_foreach sgud_loader login

}
stop_service(){

  rm -f /var/run/${DAEMON}.pid 2&>1 >/dev/null
  sguclient -k 2&>1 >/dev/null
  rm -f /var/run/sguclient.pid 2&>1 >/dev/null
  echo "SGUClient has stopped."
	
}
reload_service(){

	stop
	start
	
}
service_triggers(){

  procd_add_reload_trigger sguclient
   
}

